# Generated by Django 4.2.1 on 2023-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='star',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
